# Generated by Django 5.1.7 on 2025-03-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificação', models.CharField(max_length=100)),
                ('codigo_insumo', models.IntegerField()),
                ('descrição_insumo', models.TextField()),
                ('unidade', models.CharField(max_length=50)),
                ('origem_preço', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AC', models.FloatField(null=True)),
                ('AL', models.FloatField(null=True)),
                ('AP', models.FloatField(null=True)),
                ('AM', models.FloatField(null=True)),
                ('BA', models.FloatField(null=True)),
                ('CE', models.FloatField(null=True)),
                ('DF', models.FloatField(null=True)),
                ('ES', models.FloatField(null=True)),
                ('GO', models.FloatField(null=True)),
                ('MA', models.FloatField(null=True)),
                ('MT', models.FloatField(null=True)),
                ('MS', models.FloatField(null=True)),
                ('MG', models.FloatField(null=True)),
                ('PA', models.FloatField(null=True)),
                ('PB', models.FloatField(null=True)),
                ('PR', models.FloatField(null=True)),
                ('PE', models.FloatField(null=True)),
                ('PI', models.FloatField(null=True)),
                ('RJ', models.FloatField(null=True)),
                ('RN', models.FloatField(null=True)),
                ('RS', models.FloatField(null=True)),
                ('RO', models.FloatField(null=True)),
                ('RR', models.FloatField(null=True)),
                ('SC', models.FloatField(null=True)),
                ('SP', models.FloatField(null=True)),
                ('SE', models.FloatField(null=True)),
                ('TO', models.FloatField(null=True)),
            ],
        ),
    ]
