# Generated by Django 5.1.7 on 2025-03-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigo_insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_insumo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tabela',
            name='coodigo_insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.codigo_insumo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumos',
            name='codigo_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.codigo_insumo'),
        ),
    ]
