# Generated by Django 5.1.7 on 2025-03-17 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_codigo_insumo_tabela_coodigo_insumo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigo_insumo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='insumos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='id',
        ),
        migrations.AlterField(
            model_name='codigo_insumo',
            name='codigo_insumo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='codigo_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.codigo_insumo'),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='coodigo_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.codigo_insumo'),
        ),
    ]
